on: [push, pull_request]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        job_name: ['linux', 'windows', 'macos']

        include:
        - job_name: linux
          os: ubuntu-18.04
          shell: bash {0}

        - job_name: windows
          os: windows-latest
          shell: msys2 {0}

        - job_name: macos
          os: macos-latest
          shell: bash {0}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: hact2l-${{ matrix.job_name }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Install Archlinux
      if: matrix.job_name == 'linux'
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
    - name: Install build dependencies
      if: matrix.job_name == 'linux'
      run: |
        sudo pacman -Syu --noconfirm && sudo pacman -S gcc make
        echo "[dkp-libs]\nServer = https://pkg.devkitpro.org/packages" >> /etc/pacman.conf
        echo "[dkp-linux]\nServer = https://pkg.devkitpro.org/packages/linux/$arch/" >> /etc/pacman.conf
        sudo pacman-key --recv BC26F752D25B92CE272E0F44F7FD5492264BB9D0 --keyserver keyserver.ubuntu.com
        sudo pacman-key --lsign BC26F752D25B92CE272E0F44F7FD5492264BB9D0
        curl  https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.xz | sudo pacman -U --noconfirm
        sudo pacman -Syu --noconfirm
        sudo pacman -S switch-dev --noconfirm
        
    - name: Install MSYS2 and packages
      if: matrix.job_name == 'windows'
      uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make

    - name: Install devkit on MSYS2
      if: matrix.job_name == 'windows'
      run: |
        sed -i '$a[dkp-libs]\nServer = https://pkg.devkitpro.org/packages' /etc/pacman.conf
        sed -i '$a[dkp-windows]\nServer = https://pkg.devkitpro.org/packages/windows/$arch/' /etc/pacman.conf
        pacman-key --recv BC26F752D25B92CE272E0F44F7FD5492264BB9D0 --keyserver keyserver.ubuntu.com
        pacman-key --lsign BC26F752D25B92CE272E0F44F7FD5492264BB9D0
        curl -O https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.xz
        pacman -U devkitpro-keyring.pkg.tar.xz --noconfirm
        pacman -Syu --noconfirm
        pacman -S switch-dev --noconfirm

    - uses: actions/checkout@v1

    - run: |
        src_dir=$(mktemp --directory)
        bin_name='hac2l'
        git clone https://github.com/Atmosphere-NX/Atmosphere.git "$src_dir"
        cd "$src_dir"
        git checkout '1afb184c143f4319e5d6d4ea27260e61830c42a0'
        hac2l_src_dir="$src_dir/tools/hac2l"
        git clone https://github.com/Atmosphere-NX/hac2l.git "$hac2l_src_dir"
        cd "$hac2l_src_dir"
        git checkout '7fc1b3a32c6a870c47d7459b23fd7c7b63014186'
        make -j6 linux_x64_release
        echo -e "Moving \e[1;92m$bin_name\e[0m binary to \e[1;92m'$BIN_PATH'\e[0m"
        mv "./out/**/$bin_name" "$BIN_PATH/"

    - uses: actions/upload-artifact@v2
      with:
        name: hac2l-${{ matrix.job_name }}
        path: hac2l*
